name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save kube-ovn
        run: docker pull gitlab/gitlab-ee:latest; docker save gitlab/gitlab-ee:latest -o gitlab-latest.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: gitlab-latest.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
